apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemadmin-deployment
  labels:
    app: systemadmin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: systemadmin
  template:
    metadata:
      labels:
        app: systemadmin
    spec:
      containers:
        - name: systemadmin-container
          image: test:latest
          ports:
            - containerPort: 80
