apiVersion: v1
kind: Service
metadata:
  name: systemadmin-service
spec:
  selector:
    app: systemadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30127
  type: NodePort
